### ISSUE TITLE
If all parameters are categorical, is BO equal to random search?

### ISSUE THREAD

**Issue by chaseblack** [mlr-org/mlrMBO#423] opened 2018-04-11 21:50 UTC
Hi,
   my model parameters are all categorical, should I still use BO with RF? As my understanding, it seems similar to Random Search.
  Best

**Comment by berndbischl** [comment] 2018-04-11 21:51
hi, why should it be like RS?

**Comment by chaseblack** [comment] 2018-04-11 22:01
Hi. Because  generally there should be a metric on the parameters so that
we can compute distance. Based on this, the regression makes sense. However in
this case they can't be measured. So I guess BO applied in this case is
similar to RF or Grid Search. Would it make sense?

**Comment by berndbischl** [comment] 2018-04-11 22:08
no, i dont think so. what part in our implementation or BO with RF assumes a metric? 
or do you think that if you do normal ML, you cannot learn on spaces which are fully categorical...?

also we write these pieces of software so you can run experiments easily and try out stuff like that yourself ;-)

i just wrote that in 5 min:

```
library(mlrMBO)
set.seed(1)
configureMlr(show.learner.output = FALSE)

f = makeSingleObjectiveFunction(
  fn = function(x) {
    sum(x)
  },
  par.set = makeParamSet(
    makeDiscreteVectorParam("x", values = c(0,1), len = 50)
  ),
  has.simple.signature = TRUE
)

ctrl = makeMBOControl()
ctrl = setMBOControlTermination(ctrl, iters = 50L)
ctrl = setMBOControlInfill(ctrl, opt.focussearch.maxit = 3L, opt.focussearch.points = 2000L)

z = mbo(f, control = ctrl)
print(z$y)
print(unlist(z$x))
```

i didnt do a fully convincing statistical experiment, but when I ran that, i could either find the minimum or get very close. 

now try that with RS. that is impossible.

that being said, we are always interesed in improvements, if you notice any problems please tell us.

also it is totally ok to ask these questions, my answer should not sound too harsh.

**Comment by berndbischl** [comment] 2018-04-11 22:10
thats a 50D space. actually the functional relations seems so simple, that i find the optimum pretty early on after the initial design (?)

**Comment by chaseblack** [comment] 2018-04-11 22:16
Hi, first thank you very much for instant reply! yes I think your code
would work. Your parameters, however, are integers. While my parameters are
categories. They are not discrete variables. I think discrete variables and
categoricals are different, because the former variables do have a
metrics(orders), they are measurable. Am I right?

**Comment by chaseblack** [comment] 2018-04-11 22:25
Yes it seems reasonable. Maybe I should delve into how BO with RF works. I
will try that and have a check.
Thank you for your help :)

**Comment by berndbischl** [comment] 2018-04-11 22:33
no problem, you are welcome. 

but i am not sure, whether what we discussed has really much to do with BO....?
i think it is simply a consequence of the fact that the RF can learn in such a space. it basically learns, that if you split an a var x_i in that space, and go "left" (to 0 or "foo") the response y becomes lower.

our focussearch optimiter than simply goes to such point and evaluates them further in the region close to 0^50. at some point going exactly to that point.

**Comment by berndbischl** [comment] 2018-04-11 22:34
closing now, if you want to ask other stuff, open other issues.

**Closed by berndbischl** 2018-04-11 22:34 UTC

**Comment by berndbischl** [comment] 2018-04-11 22:36
well, i think it is valid to consider an ponder what you asked about for BO. i mainly wanted to say, that it works, in my understanding, because the RF can learn in Z^50 as a regression model. 
anyway. repeating myself now :)

**Comment by chaseblack** [comment] 2018-04-11 22:45
Well, my optimization can be simplified like this: I want to place let's
say 10 apples into let's say 5 box. So each apple have can have 5 options.
The question is how should 10 apples be placed so that the placement can
have better value(let's assume we can obtain a value for a placement,
though it seems wierd:). That's why I asked what if all parameters are all
categoricals. Do you think BO is a good idea for this problem?

**Comment by berndbischl** [comment] 2018-04-11 23:01
how expensive is one feval?

**Comment by berndbischl** [comment] 2018-04-11 23:02
and is an feval really a blackbox? so you run a piece of code to get the answer but dont know much more?

**Comment by chaseblack** [comment] 2018-04-11 23:06
About 2 mins for each placement. Would it matter?

I am also wondering instead of BO, would Reinforcement Learning, grid
search or some combinatorial Optimization methods work.

**Comment by chaseblack** [comment] 2018-04-11 23:11
Yes.  Actually, the apples are tasks of a job  and boxes are computers. The
value is the throughput of the job. So it is a black box. Well I think it
could be a white box if I consider more hearistics.

**Comment by berndbischl** [comment] 2018-04-11 23:12
so its a scheduling problem?

**Comment by chaseblack** [comment] 2018-04-11 23:13
Yes it is.

**Comment by berndbischl** [comment] 2018-04-11 23:15
and yes the runtime of an feval matters a lot. BO has considerable overhead, so it makes sense only for problems which are expensive. 

and if for all 10 apples you have 5 places, then thats 5^10 options. so how could grid search work?
and RL i dont see how this would be relevant at all.

have you talked to people how are experts in scheduling problems and considered specialized discrete optimization algos made for this....? because i think you should.

**Comment by chaseblack** [comment] 2018-04-11 23:26
So if there are 100 apples and 20 boxes. Do you think a white box method is
a better choice? Well it is very likely that apple number reach 100.

Also, I think it is a good idea to ask for advices from experts. I am doing
that.

As for RL, since apples are connected,  what I am thinking is that I first
place apple 1, and check performance, then try to place apple 2 and check,
then try apple 3, ...So there is a reward for each action (placement).
Would it make sense for RL?

Thanks :)

**Comment by jakob-r** [comment] 2018-04-13 07:24
@berndbischl Did you see issue #422
